# docker-compose.override.yml - QNAP specific optimizations
version: '3.8'

services:
  api-gateway:
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'

  auth-service:
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'

  etsy-service:
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'

  design-service:
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'

  postgres:
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
    environment:
      - POSTGRES_SHARED_BUFFERS=256MB
      - POSTGRES_EFFECTIVE_CACHE_SIZE=1GB